In [18]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

# import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [19]:
latlong = pd.read_csv('district wise centroids.csv')
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [20]:
latlong.shape

(594, 4)

In [21]:
census=pd.read_csv('india-districts-census-2011.csv')
census.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

In [22]:
census.shape

(640, 118)

In [23]:
cols=['District code','District name','Population','Male','Female','Literate','Households_with_Internet','Housholds_with_Electric_Lighting',
      'Rural_Households','Urban_Households','Hindus','Muslims','Christians','Sikhs','Buddhists','Jains','Ownership_Owned_Households','Ownership_Rented_Households',
      'Households_with_Computer','Households_with_Car_Jeep_Van','Households_with_Television',]
census=census[cols]

In [24]:
census

,District code,District name,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,Rural_Households,Urban_Households,...,Muslims,Christians,Sikhs,Buddhists,Jains,Ownership_Owned_Households,Ownership_Rented_Households,Households_with_Computer,Households_with_Car_Jeep_Van,Households_with_Television
0,1,Kupwara,870354,474190,396164,439654,762,83071,158438,23226,...,823286,1700,5600,66,39,104807,618,5256,2988,26828
1,2,Badgam,753745,398041,355704,335649,1999,90190,160649,27190,...,736054,1489,5559,47,6,98036,609,5892,5091,54170
2,3,Leh(Ladakh),133487,78971,54516,93770,574,17250,36920,17474,...,19057,658,1092,88635,103,19387,893,2150,4271,13597
3,4,Kargil,140802,77785,63017,86236,235,15824,40370,7774,...,108239,604,1171,20126,28,16646,1419,1005,1847,8008
4,5,Punch,476835,251899,224936,261724,346,62900,132139,15269,...,431279,958,11188,83,10,87711,762,3342,1731,16022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,Mahe,41816,19143,22673,36470,574,7150,0,12110,...,12856,958,3,21,14,6569,494,1484,858,6488
636,637,Karaikal,200222,97809,102413,154916,1868,47880,35618,33715,...,28835,18391,46,63,54,33788,12831,4870,2550,38869
637,638,Nicobars,36842,20727,16115,25332,57,9301,15958,0,...,1336,26077,343,119,0,7464,1282,230,193,4830
638,639,North AND Middle Andaman,105597,54861,50736,78683,388,18641,39091,1094,...,2165,21870,77,84,4,15593,6431,1193,910,14735
639,640,South Andaman,238142,127283,110859,190266,2789,52479,34901,50631,...,28912,33037,866,135,27,30470,22410,6771,5323,44400

In [25]:
latlong

                   State           District   Latitude  Longitude
0    Andaman and Nicobar    Andaman Islands  12.382571  92.822911
1    Andaman and Nicobar    Nicobar Islands   7.835291  93.511601
2         Andhra Pradesh           Adilabad  19.284514  78.813212
3         Andhra Pradesh          Anantapur  14.312066  77.460158
4         Andhra Pradesh           Chittoor  13.331093  78.927639
..                   ...                ...        ...        ...
589          West Bengal  North 24 Parganas  22.062388  88.877940
590          West Bengal           Puruliya  23.254192  86.396853
591          West Bengal  South 24 Parganas  21.854428  88.445370
592          West Bengal     Uttar Dinajpur  26.044619  88.235952
593          West Bengal     West Midnapore  22.354897  87.231014

[594 rows x 4 columns]

In [26]:
final_df=latlong.merge(census,left_on='District',right_on='District name').drop(columns=['District name'])
final_df.head()

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,...,Muslims,Christians,Sikhs,Buddhists,Jains,Ownership_Owned_Households,Ownership_Rented_Households,Households_with_Computer,Households_with_Car_Jeep_Van,Households_with_Television
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,...,275970,15422,1377,25510,617,559211,77594,45202,8338,306433
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,...,443456,20463,932,341,1417,779195,172680,48299,9915,559461
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,...,397870,24129,867,253,1322,815953,196720,67087,16296,611465
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,...,77777,77825,738,413,4149,1088823,278383,93784,25381,821421
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,...,559770,89763,764,323,3282,981115,276073,80434,17424,816849

In [27]:
final_df['sex_ratio']= round((final_df['Female']/final_df['Male'])*100)
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,...,Christians,Sikhs,Buddhists,Jains,Ownership_Owned_Households,Ownership_Rented_Households,Households_with_Computer,Households_with_Car_Jeep_Van,Households_with_Television,sex_ratio
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,...,15422,1377,25510,617,559211,77594,45202,8338,306433,100.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,...,20463,932,341,1417,779195,172680,48299,9915,559461,98.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,...,24129,867,253,1322,815953,196720,67087,16296,611465,100.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,...,77825,738,413,4149,1088823,278383,93784,25381,821421,101.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,...,89763,764,323,3282,981115,276073,80434,17424,816849,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,5357,...,13209,747,359,639,810212,12496,63525,9639,142659,94.0
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,7951,...,18102,766,348,3037,1481222,21489,79729,14050,296566,96.0
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,12787,...,33835,849,514,281,1162914,31984,77210,18658,384314,95.0
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,3551,...,8646,622,209,3052,546915,13996,32862,6602,104489,96.0
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,2883,...,16702,477,432,1324,573488,10356,31210,8150,105431,94.0

In [28]:
final_df['litracy_rate']=(final_df['Literate']/final_df['Population']*100)
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,...,Sikhs,Buddhists,Jains,Ownership_Owned_Households,Ownership_Rented_Households,Households_with_Computer,Households_with_Car_Jeep_Van,Households_with_Television,sex_ratio,litracy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,...,1377,25510,617,559211,77594,45202,8338,306433,100.0,54.112283
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,...,932,341,1417,779195,172680,48299,9915,559461,98.0,56.625244
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,...,867,253,1322,815953,196720,67087,16296,611465,100.0,63.915599
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,...,738,413,4149,1088823,278383,93784,25381,821421,101.0,63.802642
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,...,764,323,3282,981115,276073,80434,17424,816849,100.0,60.567804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,5357,...,747,359,639,810212,12496,63525,9639,142659,94.0,52.306670
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,7951,...,766,348,3037,1481222,21489,79729,14050,296566,96.0,57.093809
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,12787,...,849,514,281,1162914,31984,77210,18658,384314,95.0,67.353414
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,3551,...,622,209,3052,546915,13996,32862,6602,104489,96.0,55.455332
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,2883,...,477,432,1324,573488,10356,31210,8150,105431,94.0,49.537766

In [29]:
final_df.drop(columns=['Male','Female','Literate'],inplace=True)
final_df.head()

,State,District,Latitude,Longitude,District code,Population,Households_with_Internet,Housholds_with_Electric_Lighting,Rural_Households,Urban_Households,...,Sikhs,Buddhists,Jains,Ownership_Owned_Households,Ownership_Rented_Households,Households_with_Computer,Households_with_Car_Jeep_Van,Households_with_Television,sex_ratio,litracy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,5512,566108,597466,220248,...,1377,25510,617,559211,77594,45202,8338,306433,100.0,54.112283
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,8606,897970,902997,341431,...,932,341,1417,779195,172680,48299,9915,559461,98.0,56.625244
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,13763,944555,907970,395900,...,867,253,1322,815953,196720,67087,16296,611465,100.0,63.915599
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,22411,1297273,1199479,406362,...,738,413,4149,1088823,278383,93784,25381,821421,101.0,63.802642
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,19383,1186028,1069877,513113,...,764,323,3282,981115,276073,80434,17424,816849,100.0,60.567804

In [30]:
final_df.to_csv('india_.csv',index=False)

In [ ]:
list_of_states=list(final_df['State'].unique())

list_of_states.insert(0,'India')
list_of_states.insert(0,'')
list_of_states

['',
 'India',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [32]:
final_df.columns

Index(['State', 'District', 'Latitude', 'Longitude', 'District code',
       'Population', 'Households_with_Internet',
       'Housholds_with_Electric_Lighting', 'Rural_Households',
       'Urban_Households', 'Hindus', 'Muslims', 'Christians', 'Sikhs',
       'Buddhists', 'Jains', 'Ownership_Owned_Households',
       'Ownership_Rented_Households', 'Households_with_Computer',
       'Households_with_Car_Jeep_Van', 'Households_with_Television',
       'sex_ratio', 'litracy_rate'],
      dtype='object')

In [33]:
sorted(final_df.columns[5:])

['Buddhists',
 'Christians',
 'Hindus',
 'Households_with_Car_Jeep_Van',
 'Households_with_Computer',
 'Households_with_Internet',
 'Households_with_Television',
 'Housholds_with_Electric_Lighting',
 'Jains',
 'Muslims',
 'Ownership_Owned_Households',
 'Ownership_Rented_Households',
 'Population',
 'Rural_Households',
 'Sikhs',
 'Urban_Households',
 'litracy_rate',
 'sex_ratio']

In [34]:
import plotly.express as px
df = px.data.carshare()
fig = px.scatter_map(final_df, lat="Latitude", lon="Longitude",zoom=3)
fig.show()